source "$HOME/.config/zsh/configs/aliases.zsh"
source "$HOME/.config/zsh/configs/completion.zsh"
source "$HOME/.config/zsh/configs/interactive.zsh"
source "$HOME/.config/zsh/configs/options.zsh"
source "$HOME/.config/zsh/configs/plugins.zsh"
