export CARGO_HOME=$XDG_DATA_HOME/cargo
export GNUPGHOME=$HOME_DATA_HOME/gnupg
export LESSHISTFILE=$XDG_CACHE_HOME/history
export GTK2_RC_FILES=$XDG_CONFIG_HOME/gtk-2.0/gtkrc
export ANDROID_HOME="$XDG_DATA_HOME"/android
export GRADLE_USER_HOME="$XDG_DATA_HOME"/gradle 
export XAUTHORITY="$XDG_RUNTIME_DIR"/Xauthority
