#!/bin/sh

# Values
USER="$USER"
OS=$(lsb_release -sd | sed -e 's/"//g')
KERNEL=$(uname -sr)
UPTIME=$(uptime -p | sed -e 's/up //')
PACKAGES=$(pkgs)
SHELL=$(basename "$SHELL")
WM="awesome"
TERMINAL=$(basename "$TERM")
EDITOR=$(basename "$EDITOR")
MEDALS="                         "

# Start
echo
echo
printf "\033[1;36m${USER:-user}   \033[33m    \033[1;36m${HOSTNAME:-hostname}\033[0m
\033[1;35mUPTIME:         \033[0m  ${UPTIME:-uptime}\033[0m
\033[1;35mOS:             \033[0m  ${OS:-os}\033[0m
\033[1;35mWM:             \033[0m舘 ${WM:-wm}\033[0m
\033[1;35mKERNEL:         \033[0m  ${KERNEL:-kernel}\033[0m
\033[1;35mPACKAGES:       \033[0m  ${PACKAGES:-packages}\033[0m
\033[1;35mSHELL:          \033[0m  ${SHELL:-shell}\033[0m
\033[1;35mTERMINAL:       \033[0m  ${TERMINAL:-terminal}\033[0m
\033[1;35mEDITOR:         \033[0m  ${EDITOR:-editor}\033[0m

\033[31m${MEDALS:-medals}"

exit 0
